### ISSUE TITLE
Websocket question

### ISSUE THREAD

**Issue by crxporter** [shnhrrsn/homebridge-unifi-protect-platform#3]
Not really a feature request. I use nodered for all of my homekit needs and I’ve had a polling system set up with my UDM pro for a while now, works fine. 

But - I see you’re using websocket to get what I assume is the same information. Do you have any source or tips on how to connect to that websocket? I tried connecting to /proxy/protect/ws/updates - which accepted the connection, but I didn’t get any output. 

Any tips or links would be greatly appreciated. Feel free to just close the issue if you’ve got better stuff to do. 

Thanks!

**Comment by shnhrrsn** [comment]
Absolutely!  This is all reverse engineered, so I'll do my best based on what I've been able to discover:

If you're not getting any output at all, it's most likely because you're not fully authed.  For some reason their ws server seems to accept the connection and then just leaves it open.  It'll do the whole ping/pong thing, but otherwise it's an empty void.

Essentially your flow needs to be:

1. Request any page from UniFiOS to get the CSRF token
2. Login via `/api/auth/login` using a JSON POST for username/password
3. Make a request to `/proxy/protect/api/bootstrap` using the CSRF token from step 1 and the cookies from step 2
4. Open the WS to `/proxy/protect/ws/updates`, again passing through CSRF token from step 1 and the cookies from step 2.  Additionally, you need to take the `lastUpdateId` param from the response of step 3 and pass it through to WS as a query string parameter as such:  `/proxy/protect/ws/updates?lastUpdateId=:value`.

All of that however is the "easy" part.  At this point you will start receiving messages from the API, however they won't be simple JSON you can decode.

The websocket sends a stream of data that you need to buffer and parse through, the payload looks roughly like this for each complete message:

* 8 byte header
* metadata
* 8 byte header
* body

So every message has two pairs of header+data.  The header format is:

Byte 1: Type
Byte 2: Format
Byte 3: Is Compressed
Byte 4-8: Length of body that follows

If `Is Compressed` is `1`, you'll need to run `zlib.inflate` on the body.

For format, so far I've only ever seen the value as `1` which indicates JSON, unsure if they support other values or if it's just future proofing.

---

I'm unfamiliar with nodered but if there's someway I can allow this plugin to support it, I'm happy to.

Otherwise, it may just be easier to use this plugin as a node package and consume the stream — you can find an example of how to do that in [`dev/stream.ts`](https://github.com/shnhrrsn/homebridge-unifi-protect-platform/blob/master/dev/stream.ts).  This is a dev util I have just to monitor the ws events and doesn't actually require anything from homebridge to work.

**Comment by crxporter** [comment]
Wow! Excellent information thank you. 

I’m getting ready to build a nodered plugin (nodejs) which I will connect to the nodered implementation of hap-nodejs. 

So far I have a test websocket setup which gets json data from a couple other Unifi OS endpoints, all of the network data and such. I will have a look at your explanation and see if it is the “golden ticket” of protect push api that I’ve been searching for

**Comment by crxporter** [comment]
Oh hey. Just saw stream.ts. That might actually plug right into a nodered node. 

I’ll be sure to credit you if I steal it!

**Comment by crxporter** [comment]
I'm going to go ahead and close this for now, I might not be working on it for a while. Thanks for the input - I might be back with more questions later.

Have a great day!
